### ISSUE TITLE
./src/components/Common/ReactTable/Table.js Attempted import error: 'useColumns' is not exported from 'react-table'.

### ISSUE THREAD

**Issue by fellakmoh876** [mk48/fullstack-crud-react-node-postgresql#15]
I am getting the issue when I try to run the webclient.

```
./src/components/Common/ReactTable/Table.js
Attempted import error: 'useColumns' is not exported from 'react-table'.
```

What's the problem?

**Comment by mk48** [comment]
I am In SouthAfrica now.
don't have proper net connection. I will look into that once I back to my home country (3rd Nov)

**Comment by fellakmoh876** [comment]
Thank you for your reply. Have a nice trip and see you on Nov 3rd.

**Comment by mk48** [comment]
@fellakmoh876  I tested again and didn't get any error message. How did you try?
you have to follow these steps:

1. restore the DB backup from 'server\_db'
2. start the server
3. start web

**Comment by fellakmoh876** [comment]
Thank you for letting me know.

**Comment by mk48** [comment]
@fellakmoh876  can you please try now and let me know whether you are facing the issue still?

**Comment by mk48** [comment]
@fellakmoh876 Are you still having any issues? Can I help in anyway for you?

**Comment by mk48** [comment]
I am closing this for now, if you are facing any issues please feel free to open a new.
